project:
  type: website

website:
  title: "audioreactive"
  back-to-top-navigation: false
  navbar:
    background: transparent
    right:
      - text: about
        href: about.qmd
      - icon: github
        href: https://github.com/mroberts1
      - icon: twitter
        href: https://twitter.com
format:
  html:
    backgroundcolor: "#EFEDE5"
    theme: 
      light: [litera, ember.scss]
      dark: [quartz, ember.scss]
    css: custom.scss
linestretch: 1.2
fontsize: 0.9em
smooth-scroll: true
linkcolor: "#235440"
link-external-newwindow: true
execute:
  freeze: auto




